apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  namespace: shortly
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: migrate
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: shortly-migrate:local
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)?schema=public
